service: shifter-cron

provider:
  name: aws
  runtime: nodejs8.10

functions:
  cron:
    handler: handler.run
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: true
    environment:
      USERNAME: username
      PASSWORD: password
      SITE_ID: site-id
